-- schema.sql
DROP TABLE IF EXISTS weights;
DROP TABLE IF EXISTS meals;
DROP TABLE IF EXISTS trainings;

CREATE TABLE weights (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  weight REAL NOT NULL
);

CREATE TABLE meals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  time_slot TEXT NOT NULL,
  content TEXT NOT NULL,
  ingredients TEXT,
  image_path TEXT
);

CREATE TABLE trainings(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  event TEXT NOT NULL ,
  part TEXT NOT NULL,
  reps INTEGER NOT NULL,
  sets INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)